id: A8E44C1DD
title: Brief Windhorse Invocation
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:29:58.377192
  last_modified_at: 2022-03-01 04:29:58.377197
