id: A8E44C1DD
title: Prayer to Gyaltsen Tsemö Pung Gyen
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:29:58.384307
  last_modified_at: 2022-03-01 04:29:58.384312
