id: A8E44C1DD
title: The Swift Fulfilment of All Wishes—Offering the Flag of Windhorse
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:29:58.389856
  last_modified_at: 2022-03-01 04:29:58.389859
