id: A8E44C1DD
title: Brief Gesar Windhorse Invocation
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:29:58.373976
  last_modified_at: 2022-03-01 04:29:58.373983
