id: A8E44C1DD
title: Short Windhorse Prayer to Gesar
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:29:58.387288
  last_modified_at: 2022-03-01 04:29:58.387291
