id: A8E44C1DD
title: Daily Lungta Recitation
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:29:58.381829
  last_modified_at: 2022-03-01 04:29:58.381855
