id: A8E44C1DD
title: Raising the Windhorse
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:29:58.386127
  last_modified_at: 2022-03-01 04:29:58.386130
